'use client';

import React, { useState, useEffect } from 'react';
import type { SummaryData } from '@/types/summary';
import './SummaryDisplay.scss';

interface SummaryDisplayProps {
  data: SummaryData | null;
  isLoading: boolean;
  error?: string | null;
  onRetry?: () => void;
  onTimestampClick?: (seconds: number) => void;
}

export default function SummaryDisplay({ 
  data, 
  isLoading, 
  error, 
  onRetry, 
  onTimestampClick 
}: SummaryDisplayProps) {
  const [loadingMessage, setLoadingMessage] = useState('자막을 추출하고 있습니다...');

  // Simple loading message rotation
  useEffect(() => {
    if (!isLoading) return;
    
    const messages = [
      '자막을 추출하고 있습니다...',
      'AI가 영상을 분석하고 있습니다...',
      '요약을 생성하고 있습니다...'
    ];
    let index = 0;
    
    const interval = setInterval(() => {
        index = (index + 1) % messages.length;
        setLoadingMessage(messages[index]);
    }, 4000);

    return () => clearInterval(interval);
  }, [isLoading]);

  if (isLoading) {
    return (
      <div className="summary-display__loading text-center p-4">
        <div className="spinner-border text-primary mb-2" role="status">
          <span className="visually-hidden">Loading...</span>
        </div>
        <p className="text-muted">{loadingMessage}</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="summary-display__error alert alert-danger d-flex align-items-center justify-content-between">
        <div>
            <i className="bi bi-exclamation-triangle-fill me-2"></i>
            {error}
        </div>
        {onRetry && (
            <button className="btn btn-outline-danger btn-sm" onClick={onRetry}>
                재시도
            </button>
        )}
      </div>
    );
  }

  if (!data) return null;

  return (
    <div className="summary-display mt-4">
      {/* Key Notes */}
      <div className="summary-display__section mb-4">
        <h5 className="summary-display__title d-flex align-items-center gap-2 mb-3">
            <i className="bi bi-lightbulb-fill text-warning"></i>
            핵심 요약
        </h5>
        <ul className="summary-display__key-notes list-group">
            {data.key_notes.map((note, idx) => (
                <li key={idx} className="list-group-item">
                    • {note}
                </li>
            ))}
        </ul>
      </div>

      {/* Detailed Notes */}
      <div className="summary-display__section">
        <h5 className="summary-display__title d-flex align-items-center gap-2 mb-3">
            <i className="bi bi-journal-text text-primary"></i>
            상세 노트
        </h5>
        <div className="summary-display__detailed-notes">
            {data.detailed_notes.map((note, idx) => (
                <div key={idx} className="card mb-3">
                    <div className="card-body">
                        <div className="d-flex align-items-center mb-2">
                            <button 
                                className="btn btn-sm btn-light text-primary fw-bold me-2"
                                onClick={() => onTimestampClick?.(note.timestamp_seconds)}
                            >
                                <i className="bi bi-play-fill"></i> {note.timestamp}
                            </button>
                            <h6 className="card-title mb-0">{note.title}</h6>
                        </div>
                        <p className="card-text text-muted small">{note.content}</p>
                    </div>
                </div>
            ))}
        </div>
      </div>
      
      {/* Meta Info (Optional, debug purpose) */}
      <div className="text-end text-muted small mt-2">
        <i className="bi bi-robot"></i> Generated by {data.meta.model}
      </div>
    </div>
  );
}
