import { User } from '@/components/Admin/UserManagement/types';

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'John Administrator',
    email: 'john.admin@dvs-platform.com',
    role: 'admin',
    status: 'active',
    avatar: 'https://i.pravatar.cc/150?img=1',
    joinDate: '2024-01-15T08:00:00Z',
    lastActive: '2025-02-28T10:30:00Z',
    emailVerified: true,
    phoneVerified: true,
    country: 'United States',
    timezone: 'America/New_York',
  },
  {
    id: '2',
    name: 'Sarah Williams',
    email: 'sarah.williams@example.com',
    role: 'instructor',
    status: 'active',
    avatar: 'https://i.pravatar.cc/150?img=5',
    joinDate: '2024-03-20T10:00:00Z',
    lastActive: '2025-02-28T09:15:00Z',
    emailVerified: true,
    phoneVerified: true,
    courses: 12,
    totalEarned: 45600,
    country: 'United Kingdom',
    timezone: 'Europe/London',
    bio: 'Experienced web development instructor with 10+ years in the industry',
    skills: ['JavaScript', 'React', 'Node.js', 'TypeScript'],
  },
  {
    id: '3',
    name: 'Michael Chen',
    email: 'michael.chen@student.edu',
    role: 'student',
    status: 'active',
    avatar: 'https://i.pravatar.cc/150?img=3',
    joinDate: '2024-06-10T14:00:00Z',
    lastActive: '2025-02-27T16:45:00Z',
    emailVerified: true,
    phoneVerified: false,
    enrollments: 5,
    totalSpent: 1250,
    country: 'Canada',
    timezone: 'America/Toronto',
  },
  {
    id: '4',
    name: 'Emily Johnson',
    email: 'emily.j@design.co',
    role: 'instructor',
    status: 'active',
    avatar: 'https://i.pravatar.cc/150?img=9',
    joinDate: '2024-04-05T09:00:00Z',
    lastActive: '2025-02-28T08:00:00Z',
    emailVerified: true,
    phoneVerified: true,
    courses: 8,
    totalEarned: 32400,
    country: 'Australia',
    timezone: 'Australia/Sydney',
    skills: ['UI/UX Design', 'Figma', 'Adobe XD'],
  },
  {
    id: '5',
    name: 'David Martinez',
    email: 'david.m@techstudent.com',
    role: 'student',
    status: 'suspended',
    avatar: 'https://i.pravatar.cc/150?img=7',
    joinDate: '2024-07-22T11:30:00Z',
    lastActive: '2025-02-20T14:20:00Z',
    emailVerified: true,
    phoneVerified: false,
    enrollments: 3,
    totalSpent: 750,
    country: 'Spain',
    timezone: 'Europe/Madrid',
  },
  {
    id: '6',
    name: 'Lisa Anderson',
    email: 'lisa.anderson@admin.com',
    role: 'admin',
    status: 'active',
    avatar: 'https://i.pravatar.cc/150?img=10',
    joinDate: '2024-02-01T08:00:00Z',
    lastActive: '2025-02-28T11:00:00Z',
    emailVerified: true,
    phoneVerified: true,
    country: 'United States',
    timezone: 'America/Los_Angeles',
  },
  {
    id: '7',
    name: 'Robert Kim',
    email: 'robert.kim@instructor.edu',
    role: 'instructor',
    status: 'inactive',
    avatar: 'https://i.pravatar.cc/150?img=11',
    joinDate: '2024-05-15T13:00:00Z',
    lastActive: '2025-01-15T10:30:00Z',
    emailVerified: true,
    phoneVerified: true,
    courses: 15,
    totalEarned: 52300,
    country: 'South Korea',
    timezone: 'Asia/Seoul',
    skills: ['Python', 'Machine Learning', 'Data Science'],
  },
  {
    id: '8',
    name: 'Jennifer Brown',
    email: 'jennifer.b@learning.org',
    role: 'student',
    status: 'active',
    avatar: 'https://i.pravatar.cc/150?img=16',
    joinDate: '2024-08-30T15:00:00Z',
    lastActive: '2025-02-28T07:45:00Z',
    emailVerified: true,
    phoneVerified: true,
    enrollments: 7,
    totalSpent: 2100,
    country: 'Germany',
    timezone: 'Europe/Berlin',
  },
  {
    id: '9',
    name: 'Thomas Wilson',
    email: 'thomas.w@newbie.com',
    role: 'student',
    status: 'pending',
    avatar: 'https://i.pravatar.cc/150?img=12',
    joinDate: '2025-02-25T10:00:00Z',
    lastActive: '2025-02-25T10:00:00Z',
    emailVerified: false,
    phoneVerified: false,
    enrollments: 0,
    totalSpent: 0,
    country: 'France',
    timezone: 'Europe/Paris',
  },
  {
    id: '10',
    name: 'Maria Garcia',
    email: 'maria.garcia@instructor.pro',
    role: 'instructor',
    status: 'active',
    avatar: 'https://i.pravatar.cc/150?img=20',
    joinDate: '2024-06-01T09:00:00Z',
    lastActive: '2025-02-28T06:30:00Z',
    emailVerified: true,
    phoneVerified: true,
    courses: 10,
    totalEarned: 41200,
    country: 'Mexico',
    timezone: 'America/Mexico_City',
    skills: ['Spanish', 'Business', 'Marketing'],
  },
  {
    id: '11',
    name: 'James Taylor',
    email: 'james.taylor@student.net',
    role: 'student',
    status: 'active',
    avatar: 'https://i.pravatar.cc/150?img=14',
    joinDate: '2024-09-10T14:30:00Z',
    lastActive: '2025-02-27T18:20:00Z',
    emailVerified: true,
    phoneVerified: false,
    enrollments: 4,
    totalSpent: 980,
    country: 'India',
    timezone: 'Asia/Kolkata',
  },
  {
    id: '12',
    name: 'Amanda White',
    email: 'amanda.white@educator.com',
    role: 'instructor',
    status: 'active',
    avatar: 'https://i.pravatar.cc/150?img=23',
    joinDate: '2024-07-15T11:00:00Z',
    lastActive: '2025-02-28T05:15:00Z',
    emailVerified: true,
    phoneVerified: true,
    courses: 6,
    totalEarned: 28900,
    country: 'Brazil',
    timezone: 'America/Sao_Paulo',
    skills: ['Photography', 'Video Editing', 'Creative Arts'],
  },
  {
    id: '13',
    name: 'Kevin Liu',
    email: 'kevin.liu@techlearner.io',
    role: 'student',
    status: 'active',
    avatar: 'https://i.pravatar.cc/150?img=15',
    joinDate: '2024-10-20T16:00:00Z',
    lastActive: '2025-02-28T09:00:00Z',
    emailVerified: true,
    phoneVerified: true,
    enrollments: 8,
    totalSpent: 3200,
    country: 'Singapore',
    timezone: 'Asia/Singapore',
  },
  {
    id: '14',
    name: 'Rachel Green',
    email: 'rachel.green@inactive.com',
    role: 'student',
    status: 'inactive',
    avatar: 'https://i.pravatar.cc/150?img=25',
    joinDate: '2024-05-05T12:00:00Z',
    lastActive: '2024-12-01T15:30:00Z',
    emailVerified: true,
    phoneVerified: false,
    enrollments: 2,
    totalSpent: 450,
    country: 'Netherlands',
    timezone: 'Europe/Amsterdam',
  },
  {
    id: '15',
    name: 'Daniel Harris',
    email: 'daniel.h@businesspro.com',
    role: 'instructor',
    status: 'active',
    avatar: 'https://i.pravatar.cc/150?img=17',
    joinDate: '2024-08-12T10:00:00Z',
    lastActive: '2025-02-28T11:45:00Z',
    emailVerified: true,
    phoneVerified: true,
    courses: 9,
    totalEarned: 38700,
    country: 'Japan',
    timezone: 'Asia/Tokyo',
    skills: ['Business Strategy', 'Leadership', 'Finance'],
  },
  {
    id: '16',
    name: 'Sophia Miller',
    email: 'sophia.m@learninghub.edu',
    role: 'student',
    status: 'active',
    avatar: 'https://i.pravatar.cc/150?img=26',
    joinDate: '2024-11-01T13:30:00Z',
    lastActive: '2025-02-28T10:00:00Z',
    emailVerified: true,
    phoneVerified: false,
    enrollments: 6,
    totalSpent: 1800,
    country: 'Italy',
    timezone: 'Europe/Rome',
  },
  {
    id: '17',
    name: 'Christopher Lee',
    email: 'chris.lee@suspended.net',
    role: 'student',
    status: 'suspended',
    avatar: 'https://i.pravatar.cc/150?img=18',
    joinDate: '2024-09-25T14:00:00Z',
    lastActive: '2025-02-10T12:00:00Z',
    emailVerified: false,
    phoneVerified: false,
    enrollments: 1,
    totalSpent: 200,
    country: 'Russia',
    timezone: 'Europe/Moscow',
  },
  {
    id: '18',
    name: 'Nancy Davis',
    email: 'nancy.davis@instructor.org',
    role: 'instructor',
    status: 'active',
    avatar: 'https://i.pravatar.cc/150?img=27',
    joinDate: '2024-04-20T09:30:00Z',
    lastActive: '2025-02-28T08:30:00Z',
    emailVerified: true,
    phoneVerified: true,
    courses: 11,
    totalEarned: 43100,
    country: 'Sweden',
    timezone: 'Europe/Stockholm',
    skills: ['Web Design', 'CSS', 'HTML', 'JavaScript'],
  },
  {
    id: '19',
    name: 'Ryan Thompson',
    email: 'ryan.t@pending.user',
    role: 'student',
    status: 'pending',
    avatar: 'https://i.pravatar.cc/150?img=19',
    joinDate: '2025-02-27T16:00:00Z',
    lastActive: '2025-02-27T16:00:00Z',
    emailVerified: false,
    phoneVerified: false,
    enrollments: 0,
    totalSpent: 0,
    country: 'Norway',
    timezone: 'Europe/Oslo',
  },
  {
    id: '20',
    name: 'Patricia Clark',
    email: 'patricia.clark@admin.sys',
    role: 'admin',
    status: 'active',
    avatar: 'https://i.pravatar.cc/150?img=28',
    joinDate: '2024-03-01T08:00:00Z',
    lastActive: '2025-02-28T12:00:00Z',
    emailVerified: true,
    phoneVerified: true,
    country: 'Denmark',
    timezone: 'Europe/Copenhagen',
  },
  {
    id: '21',
    name: 'Mark Robinson',
    email: 'mark.r@student.learn',
    role: 'student',
    status: 'active',
    avatar: 'https://i.pravatar.cc/150?img=21',
    joinDate: '2024-12-10T15:00:00Z',
    lastActive: '2025-02-28T07:00:00Z',
    emailVerified: true,
    phoneVerified: true,
    enrollments: 3,
    totalSpent: 890,
    country: 'Switzerland',
    timezone: 'Europe/Zurich',
  },
  {
    id: '22',
    name: 'Jessica Moore',
    email: 'jessica.moore@teach.pro',
    role: 'instructor',
    status: 'inactive',
    avatar: 'https://i.pravatar.cc/150?img=29',
    joinDate: '2024-06-25T10:30:00Z',
    lastActive: '2025-01-05T14:00:00Z',
    emailVerified: true,
    phoneVerified: false,
    courses: 5,
    totalEarned: 21500,
    country: 'Belgium',
    timezone: 'Europe/Brussels',
    skills: ['Language Learning', 'English', 'French'],
  },
  {
    id: '23',
    name: 'Andrew Walker',
    email: 'andrew.w@newstudent.co',
    role: 'student',
    status: 'active',
    avatar: 'https://i.pravatar.cc/150?img=22',
    joinDate: '2025-01-15T11:00:00Z',
    lastActive: '2025-02-28T11:30:00Z',
    emailVerified: true,
    phoneVerified: false,
    enrollments: 2,
    totalSpent: 580,
    country: 'Ireland',
    timezone: 'Europe/Dublin',
  },
  {
    id: '24',
    name: 'Michelle Young',
    email: 'michelle.young@expert.edu',
    role: 'instructor',
    status: 'active',
    avatar: 'https://i.pravatar.cc/150?img=30',
    joinDate: '2024-09-05T09:00:00Z',
    lastActive: '2025-02-28T10:15:00Z',
    emailVerified: true,
    phoneVerified: true,
    courses: 7,
    totalEarned: 31800,
    country: 'New Zealand',
    timezone: 'Pacific/Auckland',
    skills: ['Mobile Development', 'React Native', 'Flutter'],
  },
];
